# swagger_doc/group/get.yml
swagger: '2.0'
info:
  title: 'My API'
  description: 'API for managing groups and participants'
  version: '1.0'
host: 'localhost:8080'
basePath: '/'
tags:
- name: 'Group'
  description: 'Operations with groups'
paths:
  /group:
    get:
      tags:
      - 'Group'
      summary: 'Get all groups'
      responses:
        '200':
          description: 'Successful response'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Group'
        '404':
          description: 'Group not found'
      produces:
      - 'application/json'
definitions:
  Group:
    type: 'object'
    properties:
      id:
        type: 'integer'
      name:
        type: 'string'
      description:
        type: 'string'
      participants:
        type: 'array'
        items:
          $ref: '#/definitions/Participant'
  Participant:
    type: 'object'
    properties:
      id:
        type: 'integer'
      name:
        type: 'string'
      wish:
        type: 'string'
      recipient:
        type: 'integer'
